# SAF link metadata for project creation
treeUri=content://com.android.externalstorage.documents/tree/4781-1AF2%3A
treeLabel=4781-1AF2
treeSummary=4781-1AF2
projectUri=content://com.android.externalstorage.documents/tree/4781-1AF2%3A/document/4781-1AF2%3AACYCLIC
